# Generated by Django 5.0.6 on 2025-07-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='LinkMapping',
        ),
    ]
