# Generated by Django 5.2.4 on 2025-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_question_linkmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkmapping',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='linkmapping',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='linkmapping',
            name='hash',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='linkmapping',
            name='original_url',
            field=models.CharField(max_length=2000),
        ),
    ]
