# Generated by Django 5.2.4 on 2025-07-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_linkmapping_is_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmapping',
            name='hash',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
